ktl_dbt:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: "{{ env_var('SCHEMA_NAME') }}"
      host: local[*]
      port: 7077
      threads: 8 
      connect_timeout: 60
      connect_retries: 3
      retry_all: true
      conf:
        "spark.hadoop.hive.metastore.uris": "thrift://192.168.1.156:9083"
        "spark.sql.extensions": "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions"
        "spark.sql.catalog.demo": "org.apache.iceberg.spark.SparkCatalog"
        "spark.sql.catalog.demo.type": "hive"
        "spark.sql.catalog.demo.uri": "thrift://192.168.1.156:9083"
        "spark.sql.catalog.demo.io-impl": "org.apache.iceberg.aws.s3.S3FileIO"
        "spark.sql.catalog.demo.s3.endpoint": "http://192.168.1.151"
        "spark.sql.catalog.demo.warehouse": "s3a://data/warehouse/"
        "spark.sql.catalog.spark_catalog": "org.apache.iceberg.spark.SparkSessionCatalog"
        "spark.sql.catalog.spark_catalog.type": "hive"
        "spark.hadoop.fs.s3a.endpoint": "http://192.168.1.151"
        "spark.hadoop.fs.s3a.access.key": "{{ env_var('AWS_ACCESS_KEY_ID', 'Vl21ZDUEq1XNiDDN') }}"
        "spark.hadoop.fs.s3a.secret.key": "{{ env_var('AWS_SECRET_ACCESS_KEY', 'Su9omOppqPvl9q59ABdIfzwOzDi1PpgZ') }}"
        "spark.hadoop.fs.s3a.path.style.access": "true"
        "spark.hadoop.fs.s3a.ssl.enabled": "false"
        "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
        "spark.sql.defaultCatalog": "demo"

    prod:
      type: spark
      method: session
      schema: analytics_prod
      host: spark-master
      port: 7077
      threads: 8 
      connect_timeout: 60
      connect_retries: 3
      retry_all: true