{{ config(
    materialized = 'table',
    file_format='iceberg',
    schema='backfill'
) }}

{#- Backfill version of fact_dp_summary, references fact_dp_detail_backfill -#}

WITH CTE_DP_CURR AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           DP.D_BRANCH_ID, DP.CUSTOMER_TYPE, DP.ACCOUNT_TYPE, DP.LCY_CURR_BALANCE 
    FROM {{ ref('fact_dp_detail_backfill') }} DP
    JOIN {{ ref('dim_time') }} TT ON DP.COB_DATE = TT.COB_DATE  
),
CTE_DP_DAGO AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           DP.D_BRANCH_ID, DP.CUSTOMER_TYPE, DP.ACCOUNT_TYPE, DP.LCY_CURR_BALANCE 
    FROM {{ ref('fact_dp_detail_backfill') }} DP
    JOIN {{ ref('dim_time') }} TT ON DP.COB_DATE = TT.DAY_AGO
),
CTE_DP_ELM AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           DP.D_BRANCH_ID, DP.CUSTOMER_TYPE, DP.ACCOUNT_TYPE, DP.LCY_CURR_BALANCE
    FROM {{ ref('fact_dp_detail_backfill') }} DP
    JOIN {{ ref('dim_time') }} TT ON DP.COB_DATE = TT.ELM_DATE
),
CTE_DP_ELY AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           DP.D_BRANCH_ID, DP.CUSTOMER_TYPE, DP.ACCOUNT_TYPE, DP.LCY_CURR_BALANCE 
    FROM {{ ref('fact_dp_detail_backfill') }} DP
    JOIN {{ ref('dim_time') }} TT ON DP.COB_DATE = TT.ELY_DATE
),
CTE_DP_MTD AS (
    SELECT SS.COB_DATE, SS.ELM_DATE, SS.ELY_DATE, SS.DAY_AGO, SS.BOM_DATE, SS.DAY_IN_MONTH,
           SS.D_BRANCH_ID, SS.CUSTOMER_TYPE, SS.ACCOUNT_TYPE, SUM(SS.LCY_CURR_BALANCE) LCY_CURR_BALANCE
    FROM (           
        SELECT DP.COB_DATE, DP.ELM_DATE, DP.ELY_DATE, DP.DAY_AGO, DP.BOM_DATE, DP.DAY_IN_MONTH,
               DP.D_BRANCH_ID, DP.CUSTOMER_TYPE, DP.ACCOUNT_TYPE, TT.LCY_CURR_BALANCE
        FROM CTE_DP_CURR DP
        JOIN CTE_DP_CURR TT ON TT.COB_DATE BETWEEN DP.BOM_DATE AND DP.COB_DATE  
              AND DP.D_BRANCH_ID = TT.D_BRANCH_ID AND DP.CUSTOMER_TYPE=TT.CUSTOMER_TYPE AND DP.ACCOUNT_TYPE=TT.ACCOUNT_TYPE   
    ) SS
    GROUP BY SS.COB_DATE, SS.ELM_DATE, SS.ELY_DATE, SS.DAY_AGO, SS.BOM_DATE, SS.DAY_IN_MONTH,
             SS.D_BRANCH_ID, SS.CUSTOMER_TYPE, SS.ACCOUNT_TYPE                    
)
SELECT AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
       AA.CUSTOMER_TYPE, AA.ACCOUNT_TYPE, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME,
       SUM(AA.BAL_TODAY) BAL_TODAY, SUM(AA.BAL_DAGO) BAL_DAGO, SUM(AA.BAL_ELM) BAL_ELM,
       SUM(AA.BAL_ELY) BAL_ELY, SUM(AA.BAL_MTD) BAL_MTD, SUM(AA.BAL_MTD)/AA.DAY_IN_MONTH AS AVG_BAL_MTD
FROM (
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, CUSTOMER_TYPE, ACCOUNT_TYPE,
           LCY_CURR_BALANCE BAL_TODAY, 0 BAL_DAGO, 0 BAL_ELM, 0 BAL_ELY, 0 BAL_MTD FROM CTE_DP_CURR
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, CUSTOMER_TYPE, ACCOUNT_TYPE,
           0, LCY_CURR_BALANCE, 0, 0, 0 FROM CTE_DP_DAGO   
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, CUSTOMER_TYPE, ACCOUNT_TYPE,
           0, 0, LCY_CURR_BALANCE, 0, 0 FROM CTE_DP_ELM
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, CUSTOMER_TYPE, ACCOUNT_TYPE,
           0, 0, 0, LCY_CURR_BALANCE, 0 FROM CTE_DP_ELY 
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, CUSTOMER_TYPE, ACCOUNT_TYPE,
           0, 0, 0, 0, LCY_CURR_BALANCE FROM CTE_DP_MTD
) AA
JOIN {{ ref('dim_branch') }} BB ON BB.D_BRANCH_ID=AA.D_BRANCH_ID
GROUP BY AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
         AA.CUSTOMER_TYPE, AA.ACCOUNT_TYPE, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME
