{{ config(
    materialized = 'table',
    file_format='iceberg',
    schema='backfill'
) }}

{#- Backfill version of fact_pl_summary, references fact_pl_detail_backfill -#}

WITH CTE_PL_CURR AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           PL.D_BRANCH_ID, PL.PL_CODE, PL.LCY_OUTSTND, PL.LCY_OUTSTND AS LCY_BALANCE
    FROM {{ ref('fact_pl_detail_backfill') }} PL
    JOIN {{ ref('dim_time') }} TT ON PL.COB_DATE = TT.COB_DATE
    WHERE TT.COB_DATE = TO_DATE('31/12/2024','dd/MM/yyyy')                                 
    UNION ALL                            
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           PL.D_BRANCH_ID, PL.PL_CODE, PL.LCY_OUTSTND,   
           SUM(PL.LCY_OUTSTND) OVER (PARTITION BY PL.D_BRANCH_ID,PL.PL_CODE ORDER BY TT.COB_DATE,PL.D_BRANCH_ID,PL.PL_CODE) AS LCY_BALANCE
    FROM {{ ref('fact_pl_detail_backfill') }} PL
    JOIN {{ ref('dim_time') }} TT ON PL.COB_DATE = TT.COB_DATE 
    WHERE TT.COB_DATE <> TO_DATE('31/12/2024','dd/MM/yyyy')                                                      
),    
CTE_PL_DAGO AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           PL.D_BRANCH_ID, PL.PL_CODE, PL.LCY_OUTSTND, PL.LCY_BALANCE
    FROM CTE_PL_CURR PL
    JOIN {{ ref('dim_time') }} TT ON PL.COB_DATE = TT.DAY_AGO
    WHERE PL.LCY_BALANCE <> 0                      
),
CTE_PL_ELM AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           PL.D_BRANCH_ID, PL.PL_CODE, PL.LCY_OUTSTND, PL.LCY_BALANCE
    FROM CTE_PL_CURR PL
    JOIN {{ ref('dim_time') }} TT ON PL.COB_DATE = TT.ELM_DATE
    WHERE PL.LCY_BALANCE <> 0                          
),
CTE_PL_ELY AS (
    SELECT TT.COB_DATE, CAST(TT.ELM_DATE AS DATE) ELM_DATE, CAST(TT.ELY_DATE AS DATE) ELY_DATE,
           CAST(TT.DAY_AGO AS DATE) DAY_AGO, CAST(TT.BOM_DATE AS DATE) BOM_DATE, TT.DAY_IN_MONTH,
           PL.D_BRANCH_ID, PL.PL_CODE, PL.LCY_OUTSTND, PL.LCY_BALANCE
    FROM CTE_PL_CURR PL
    JOIN {{ ref('dim_time') }} TT ON PL.COB_DATE = TT.ELY_DATE
    WHERE PL.LCY_BALANCE <> 0                             
),
CTE_PL_UNION AS (
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, PL_CODE,
           CASE WHEN LEFT(PL_CODE,1)='8' THEN LCY_BALANCE ELSE LCY_OUTSTND END BAL_TODAY,
           0 AS BAL_DAGO, 0 AS BAL_ELM, 0 AS BAL_ELY FROM CTE_PL_CURR
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, PL_CODE,
           0, CASE WHEN LEFT(PL_CODE,1)='8' THEN LCY_BALANCE ELSE LCY_OUTSTND END, 0, 0 FROM CTE_PL_DAGO   
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, PL_CODE,
           0, 0, CASE WHEN LEFT(PL_CODE,1)='8' THEN LCY_BALANCE ELSE LCY_OUTSTND END, 0 FROM CTE_PL_ELM
    UNION ALL
    SELECT COB_DATE, ELM_DATE, ELY_DATE, DAY_AGO, BOM_DATE, DAY_IN_MONTH, D_BRANCH_ID, PL_CODE,
           0, 0, 0, LCY_BALANCE FROM CTE_PL_ELY 
)
SELECT AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
       'DETAIL' AS PL_GRP, CC.PL_CODE, CC.PL_NAME, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME,
       SUM(AA.BAL_TODAY) BAL_TODAY, SUM(AA.BAL_DAGO) BAL_DAGO, SUM(AA.BAL_ELM) BAL_ELM, SUM(AA.BAL_ELY) BAL_ELY, MAX(BB.NBR_STAFF) NBR_STAFF
FROM CTE_PL_UNION AA
JOIN {{ ref('dim_branch') }} BB ON BB.D_BRANCH_ID=AA.D_BRANCH_ID
JOIN {{ ref('dim_pl_item') }} CC ON CC.PL_CODE = AA.PL_CODE    
WHERE CC.PL_MAIN_CODE IN (7,8,9) 
GROUP BY AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
         CC.PL_CODE, CC.PL_NAME, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME              
UNION ALL
SELECT AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
       'TOTAL' AS PL_GRP, CC.PL_MAIN_CODE AS PL_CODE, CC.PL_MAIN_NAME AS PL_NAME, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME,
       SUM(AA.BAL_TODAY) BAL_TODAY, SUM(AA.BAL_DAGO) BAL_DAGO, SUM(AA.BAL_ELM) BAL_ELM, SUM(AA.BAL_ELY) BAL_ELY, MAX(BB.NBR_STAFF) NBR_STAFF
FROM CTE_PL_UNION AA
JOIN {{ ref('dim_branch') }} BB ON BB.D_BRANCH_ID=AA.D_BRANCH_ID
JOIN {{ ref('dim_pl_item') }} CC ON CC.PL_CODE = AA.PL_CODE 
WHERE CC.PL_MAIN_CODE IN (7,8,9)                                                                             
GROUP BY AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
         CC.PL_MAIN_CODE, CC.PL_MAIN_NAME, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME    
UNION ALL
SELECT AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
       'TOTAL' AS PL_GRP, 10 AS PL_CODE, 'Lợi nhuận trước thuế' AS PL_NAME, BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME,
       SUM(CASE WHEN CC.PL_MAIN_CODE =7 THEN AA.BAL_TODAY ELSE -AA.BAL_TODAY END) BAL_TODAY,
       SUM(CASE WHEN CC.PL_MAIN_CODE =7 THEN AA.BAL_DAGO ELSE -AA.BAL_DAGO END) BAL_DAGO,
       SUM(CASE WHEN CC.PL_MAIN_CODE =7 THEN AA.BAL_ELM ELSE -AA.BAL_ELM END) BAL_ELM,
       SUM(CASE WHEN CC.PL_MAIN_CODE =7 THEN AA.BAL_ELY ELSE -AA.BAL_ELY END) BAL_ELY,
       MAX(BB.NBR_STAFF) NBR_STAFF
FROM CTE_PL_UNION AA
JOIN {{ ref('dim_branch') }} BB ON BB.D_BRANCH_ID=AA.D_BRANCH_ID
JOIN {{ ref('dim_pl_item') }} CC ON CC.PL_CODE = AA.PL_CODE 
WHERE CC.PL_MAIN_CODE IN (7,8,9)                                                                             
GROUP BY AA.COB_DATE, AA.ELM_DATE, AA.ELY_DATE, AA.DAY_AGO, AA.BOM_DATE, AA.DAY_IN_MONTH, AA.D_BRANCH_ID,
         BB.BRANCH_CODE, BB.BRANCH_NAME, BB.PARENT_CODE, BB.PARENT_NAME, BB.KV_NAME
